name: unicode
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6

  # DI & State management
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0

  # Local
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0

  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  background_fetch: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.12

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/english/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/english/Poppins-Light.ttf
          weight: 300
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/arabic/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/arabic/Cairo-Light.ttf
          weight: 300